import uuid
import logging
from sqlalchemy.future import select
from sqlalchemy.ext.asyncio import AsyncSession
from app.models.bot_flow import BotFlow
from app.api.deps import redis_client

logger = logging.getLogger(__name__)

class FlowEngine:
    
    @staticmethod
    async def evaluate_message(db: AsyncSession, business_id: uuid.UUID, conversation_id: str, content: str, simulate_state: dict = None) -> dict:
        """
        Interprets flow logic.
        simulate_state allows bypassing DB to run raw logic arrays (from Simulator payload).
        Returns:
            {
                "handled": bool, # True if flow took over (whether it finished or waits)
                "response": str,  # Static messages generated by Action nodes 
                "ai_handoff": bool, # True if reached an AI Handover node
                "ai_tone": str, # Tone injected if ai_handoff is True
                "intent": str
            }
        """
        output = {
            "handled": False,
            "response": "",
            "ai_handoff": False,
            "ai_tone": None,
            "intent": "none"
        }
        
        session_key = f"flow_session:{conversation_id}"
        current_node_id = await redis_client.get(session_key) 
        
        active_flows = []
        if simulate_state:
            active_flows = [{"id": "simulate", "flow_logic_state": simulate_state}]
        else:
            flows_res = await db.execute(
                select(BotFlow).where(
                    BotFlow.business_id == business_id,
                    BotFlow.is_active == True
                ).order_by(BotFlow.priority.desc())
            )
            active_flows = flows_res.scalars().all()

        msg_lower = content.strip().lower()

        async def execute_node(flow_id, node_id, graph_nodes):
            res_texts = []
            curr_id = node_id
            
            while curr_id:
                node = graph_nodes.get(curr_id)
                if not node:
                    await redis_client.delete(session_key)
                    break
                    
                n_type = node.get("type")
                payload = node.get("payload", {})
                
                if n_type == "action":
                    res_texts.append(payload.get("responseText", ""))
                    next_nodes = node.get("next", [])
                    if len(next_nodes) > 0:
                        curr_id = next_nodes[0]
                    else:
                        await redis_client.delete(session_key)
                        curr_id = None
                        
                elif n_type == "wait_for_input":
                    await redis_client.setex(session_key, 86400, f"{flow_id}::{curr_id}")
                    break
                    
                elif n_type == "ai_handover":
                    output["ai_handoff"] = True
                    output["ai_tone"] = payload.get("tone", "tone_professional")
                    output["ai_instructions"] = payload.get("aiInstructions", "")
                    await redis_client.delete(session_key)
                    break
                else:
                    next_nodes = node.get("next", [])
                    if len(next_nodes) > 0:
                        curr_id = next_nodes[0]
                    else:
                        await redis_client.delete(session_key)
                        curr_id = None
                        
            if res_texts:
                output["response"] = "\n".join(res_texts)
            output["handled"] = True
            output["intent"] = "flow_match"
            return output

        if current_node_id:
            try:
                flow_id, locked_node_id = current_node_id.split("::")
            except ValueError:
                await redis_client.delete(session_key)
                return output
                
            target_flow = next((f for f in active_flows if str(f.id if hasattr(f, 'id') else f['id']) == flow_id), None)
            if target_flow:
                logic_state = target_flow.flow_logic_state if hasattr(target_flow, 'flow_logic_state') else target_flow.get("flow_logic_state")
                nodes_map = logic_state.get("nodes", {})
                node = nodes_map.get(locked_node_id)
                
                if node and node.get("type") == "wait_for_input":
                    var_name = node.get("payload", {}).get("variableName")
                    if var_name:
                        var_key = f"crm_vars:{conversation_id}"
                        await redis_client.hset(var_key, var_name, content)
                    
                    next_nodes = node.get("next", [])
                    if len(next_nodes) > 0:
                        return await execute_node(flow_id, next_nodes[0], nodes_map)
                    else:
                        await redis_client.delete(session_key)
                        output["handled"] = True
                        output["intent"] = "flow_captured"
                        return output
            
            await redis_client.delete(session_key)

        for flow in active_flows:
            logic_state = flow.flow_logic_state if hasattr(flow, 'flow_logic_state') else flow.get("flow_logic_state")
            if not logic_state: continue
            
            triggers = logic_state.get("triggers", [])
            nodes_map = logic_state.get("nodes", {})
            
            matched_node = None
            for trigger in triggers:
                keywords = trigger.get("keywords", [])
                node_id = trigger.get("node_id")
                for kw in keywords:
                    if kw and kw.lower() in msg_lower:
                        matched_node = node_id
                        break
                if matched_node: break
                
            if matched_node:
                f_id = str(flow.id if hasattr(flow, 'id') else flow['id'])
                trigger_node = nodes_map.get(matched_node, {})
                next_nodes = trigger_node.get("next", [])
                
                if len(next_nodes) > 0:
                    return await execute_node(f_id, next_nodes[0], nodes_map)
                else: 
                    output["handled"] = True
                    return output

        return output
