"""add flow jsonb states

Revision ID: b7b51abbe8aa
Revises: a1b2c3d4e5f6
Create Date: 2026-04-17 19:49:05.644427

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b7b51abbe8aa'
down_revision: Union[str, None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bot_flows', sa.Column('flow_ui_state', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('bot_flows', sa.Column('flow_logic_state', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.drop_index('ix_bot_flows_id', table_name='bot_flows')
    op.drop_index('ix_knowledge_chunks_id', table_name='knowledge_chunks')
    op.drop_index('knowledge_chunks_embedding_idx', table_name='knowledge_chunks', postgresql_using='hnsw')
    op.add_column('messages', sa.Column('intent', sa.String(length=50), nullable=True))
    op.add_column('messages', sa.Column('model_used', sa.String(length=50), nullable=True))
    op.add_column('messages', sa.Column('token_count', sa.Integer(), nullable=True))
    op.drop_index('ix_template_messages_id', table_name='template_messages')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_template_messages_id', 'template_messages', ['id'], unique=False)
    op.drop_column('messages', 'token_count')
    op.drop_column('messages', 'model_used')
    op.drop_column('messages', 'intent')
    op.create_index('knowledge_chunks_embedding_idx', 'knowledge_chunks', ['embedding'], unique=False, postgresql_using='hnsw')
    op.create_index('ix_knowledge_chunks_id', 'knowledge_chunks', ['id'], unique=False)
    op.create_index('ix_bot_flows_id', 'bot_flows', ['id'], unique=False)
    op.drop_column('bot_flows', 'flow_logic_state')
    op.drop_column('bot_flows', 'flow_ui_state')
    # ### end Alembic commands ###
