"""add ai_tone

Revision ID: c4379d9d1835
Revises: 5f723cad2fe7
Create Date: 2026-04-05 22:10:50.445290

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c4379d9d1835'
down_revision: Union[str, None] = '5f723cad2fe7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('businesses', sa.Column('ai_tone', sa.String(length=50), nullable=False, server_default='Professional'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('businesses', 'ai_tone')
    # ### end Alembic commands ###
