"""add custom_fields to customers

Revision ID: 39654aa63fa1
Revises: b7b51abbe8aa
Create Date: 2026-04-18 13:13:46.114707

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '39654aa63fa1'
down_revision: Union[str, None] = 'b7b51abbe8aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('email', sa.String(length=255), nullable=True))
    op.add_column('customers', sa.Column('custom_fields', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customers', 'custom_fields')
    op.drop_column('customers', 'email')
    # ### end Alembic commands ###
