"""add language to business

Revision ID: da83bae47c60
Revises: 847e2b47c42d
Create Date: 2026-04-07 12:40:45.797567

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da83bae47c60'
down_revision: Union[str, None] = '847e2b47c42d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('businesses', sa.Column('language', sa.String(length=50), server_default='ar', nullable=False))
    op.create_index('ix_conv_biz_cust', 'conversations', ['business_id', 'customer_id'], unique=False)
    op.create_index('ix_messages_conv_created', 'messages', ['conversation_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_messages_conv_created', table_name='messages')
    op.drop_index('ix_conv_biz_cust', table_name='conversations')
    op.drop_column('businesses', 'language')
    # ### end Alembic commands ###
