"""Phase 10 AI Evolution

Revision ID: 32ff089d34c7
Revises: 8c5028ad94ae
Create Date: 2026-04-06 03:25:32.301809

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '32ff089d34c7'
down_revision: Union[str, None] = '8c5028ad94ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('tags', sa.JSON(), nullable=True))
    op.add_column('messages', sa.Column('media_url', sa.String(), nullable=True))
    op.add_column('messages', sa.Column('campaign_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'campaign_id')
    op.drop_column('messages', 'media_url')
    op.drop_column('customers', 'tags')
    # ### end Alembic commands ###
