"""Add SystemErrorLog

Revision ID: 52a291cac798
Revises: 7742e03b432d
Create Date: 2026-04-06 01:53:06.500222

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52a291cac798'
down_revision: Union[str, None] = '7742e03b432d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system_error_logs',
    sa.Column('business_id', sa.UUID(), nullable=True),
    sa.Column('error_type', sa.String(length=100), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_error_logs_business_id'), 'system_error_logs', ['business_id'], unique=False)
    op.create_index(op.f('ix_system_error_logs_error_type'), 'system_error_logs', ['error_type'], unique=False)
    op.create_index(op.f('ix_system_error_logs_timestamp'), 'system_error_logs', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_system_error_logs_timestamp'), table_name='system_error_logs')
    op.drop_index(op.f('ix_system_error_logs_error_type'), table_name='system_error_logs')
    op.drop_index(op.f('ix_system_error_logs_business_id'), table_name='system_error_logs')
    op.drop_table('system_error_logs')
    # ### end Alembic commands ###
