"""add_message_credits

Revision ID: c7bf8a0ae3a8
Revises: 39654aa63fa1
Create Date: 2026-04-19 11:57:43.484778

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c7bf8a0ae3a8'
down_revision: Union[str, None] = '39654aa63fa1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('businesses', sa.Column('message_credits', sa.Integer(), server_default='500', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('businesses', 'message_credits')
    # ### end Alembic commands ###
