"""Add product image_url

Revision ID: 29e55efb0074
Revises: 8c75728cb8a3
Create Date: 2026-04-05 20:13:13.903518

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '29e55efb0074'
down_revision: Union[str, None] = '8c75728cb8a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_business_created_at_desc', table_name='businesses')
    op.add_column('products', sa.Column('image_url', sa.String(length=1000), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'image_url')
    op.create_index('idx_business_created_at_desc', 'businesses', [sa.text('created_at DESC')], unique=False)
    # ### end Alembic commands ###
