"""add_item_type_duration

Revision ID: 7742e03b432d
Revises: 7a5ce6ed0a6a
Create Date: 2026-04-06 00:08:18.141959

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7742e03b432d'
down_revision: Union[str, None] = '7a5ce6ed0a6a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('item_type', sa.String(length=50), nullable=False, server_default='product'))
    op.add_column('products', sa.Column('duration', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'duration')
    op.drop_column('products', 'item_type')
    # ### end Alembic commands ###
