"""Add response_time to messages

Revision ID: 8c5028ad94ae
Revises: 52a291cac798
Create Date: 2026-04-06 02:54:57.515984

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c5028ad94ae'
down_revision: Union[str, None] = '52a291cac798'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('response_time', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'response_time')
    # ### end Alembic commands ###
