"""add flow jsonb states

Revision ID: b7b51abbe8aa
Revises: a1b2c3d4e5f6
Create Date: 2026-04-17 19:49:05.644427

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b7b51abbe8aa'
down_revision: Union[str, None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bot_flows', sa.Column('flow_ui_state', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('bot_flows', sa.Column('flow_logic_state', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bot_flows', 'flow_logic_state')
    op.drop_column('bot_flows', 'flow_ui_state')
    # ### end Alembic commands ###
