"""Add Phase 5 fields nullable

Revision ID: 7a5ce6ed0a6a
Revises: c4379d9d1835
Create Date: 2026-04-05 23:27:33.154893

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a5ce6ed0a6a'
down_revision: Union[str, None] = 'c4379d9d1835'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('businesses', sa.Column('bank_details', sa.JSON(), nullable=True))
    op.add_column('businesses', sa.Column('knowledge_base', sa.String(), nullable=True))
    op.add_column('businesses', sa.Column('sheet_url', sa.String(), nullable=True))
    op.add_column('businesses', sa.Column('logo_url', sa.String(), nullable=True))
    op.add_column('businesses', sa.Column('primary_color', sa.String(length=50), nullable=True))
    op.add_column('conversations', sa.Column('lead_priority', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conversations', 'lead_priority')
    op.drop_column('businesses', 'primary_color')
    op.drop_column('businesses', 'logo_url')
    op.drop_column('businesses', 'sheet_url')
    op.drop_column('businesses', 'knowledge_base')
    op.drop_column('businesses', 'bank_details')
    # ### end Alembic commands ###
