"""multi_staff_support

Revision ID: 74ac0aafb09e
Revises: c250edff9788
Create Date: 2026-04-09 15:00:41.310094

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '74ac0aafb09e'
down_revision: Union[str, None] = 'c250edff9788'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('staff_name', sa.String(length=255), nullable=True))
    op.add_column('businesses', sa.Column('staff_members', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('businesses', 'staff_members')
    op.drop_column('appointments', 'staff_name')
    # ### end Alembic commands ###
