"""add_notification_settings

Revision ID: c250edff9788
Revises: da83bae47c60
Create Date: 2026-04-09 14:17:11.309894

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c250edff9788'
down_revision: Union[str, None] = 'da83bae47c60'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('businesses', sa.Column('notification_email', sa.String(length=255), nullable=True))
    op.add_column('businesses', sa.Column('notification_telegram', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('businesses', 'notification_telegram')
    op.drop_column('businesses', 'notification_email')
    # ### end Alembic commands ###
